### ISSUE TITLE
How to install using Xcode

### ISSUE THREAD

**Issue by yd021976** [PrivateFrameworks/MediaRemote#2]
Hello and thanks for your work.

Can you give informations on how to install your framework with Xcode (not using Swift package manager) ?

Thank you !

**Comment by DimitarNestorov** [comment]
You could add this repo as a Git submodule and create an Xcode workspace with a second Xcode project, add the sources in the second project, and set your project to depend on the new project.
I don't have plans to add support for other package managers. Why can't you use Swift Package Manager?
